### ISSUE TITLE
Incorrect import in example

### ISSUE THREAD

**Issue by mathDR** [ntasfi/PyGame-Learning-Environment#1]
The import line
from ple.games.raycast_maze import RaycastMaze

should read
from ple.games.raycastmaze import RaycastMaze

**Comment by ntasfi** [comment]
Which file?

**Comment by mathDR** [comment]
examples/random_agent.py

**Comment by ntasfi** [comment]
fixed! thank you!

**Comment by mathDR** [comment]
Now its fixed.
