### ISSUE TITLE
Running the example `keras_nonvis.py` fails

### ISSUE THREAD

**Issue by prodicus** [ntasfi/PyGame-Learning-Environment#10]
Hey @ntasfi . Thanks for putting the `Dockerfile` up for everybody

What I did was

```sh
$ wget http://raw.githubusercontent.com/ntasfi/PyGame-Learning-Environment/master/docker/Dockerfile
$ docker build -t prodicus/pygame .
$ docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY prodicus/pygame /bin/bash
```
I get the following error inside the docker container, 

```sh
root@9bacfcf2f0a4:/ple/examples# python keras_nonvis.py 
Using Theano backend.
No protocol specified
No protocol specified
No protocol specified
Fatal Python error: (pygame parachute) Segmentation Fault
Aborted (core dumped)
root@9bacfcf2f0a4:/ple/examples# 
```

What could be the cause of the problem?

***

Relevant information

```sh
$ docker --version
Docker version 1.11.2, build b9f10c9

$ uname -r
4.4.0-28-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

**Comment by EderSantana** [comment]
it seems like it is not forwarding the display correctly. I got it working on my mac and copied the instructions for ubuntu. But it seems like I missed something. I tried asking for help:
https://github.com/jfrazelle/dockerfiles/issues/129

but didn't get enough information. I was originally inspired by this example:
https://github.com/jfrazelle/dockerfiles/blob/master/atom/Dockerfile#L18-L19

if you find a solution please let me know and I'll fix it. Thanks!

**Comment by ntasfi** [comment]
Is this resolved? @prodicus

**Comment by ntasfi** [comment]
Closing issue as no response from OP.

**Comment by mrdrozdov** [comment]
On mac, installing xquartz helped with this issue for me.
