### ISSUE TITLE
"TabError: inconsistent use of tabs and spaces" on Python 3

### ISSUE THREAD

**Issue by gregretkowski** [ntasfi/PyGame-Learning-Environment#11]
Hello,
  I'm trying out your code on Python 3 and have found a problem in that python 3 disallows mixing tabs and spaces for indentation. As a result the library doesn't work /w 3. For some context around this see:

http://stackoverflow.com/questions/19295519/indentation-error-with-python-3-3-when-python2-7-works-well

You can probably change all the files in bulk using sed, like in this example:

http://stackoverflow.com/questions/11094383/how-can-i-convert-tabs-to-spaces-in-every-file-of-a-directory

**Comment by ntasfi** [comment]
@gregretkowski I put PLE through autopep8. Can you let me know if it works now?

**Comment by gregretkowski** [comment]
Looks good. I grepped through the source and all the tabs are removed. Thanks!
