### ISSUE TITLE
Error raycast.py

### ISSUE THREAD

**Issue by talpay** [ntasfi/PyGame-Learning-Environment#13]
The main of raycast.py has a small error, namely that it's not passing any "actions" parameter:

`TypeError: __init__() takes exactly 12 arguments (11 given)`

which refers to this call:
```
rc = RayCastPlayer(
        map_grid,
        init_pos,
        init_dir,
        width,
        height,
        resolution,
        move_speed,
        turn_speed,
        plane,
        block_types
    )
```

**Comment by ntasfi** [comment]
@talpay ty! good catch. pushed a fix.
