### ISSUE TITLE
ImportError: No module named 'games'

### ISSUE THREAD

**Issue by wjiangcmu** [ntasfi/PyGame-Learning-Environment#15]
OSX 10.11, Python 3.5.2
All required packages are well installed, but still get following error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Name/workspace/PyGame-Learning-Environment/ple/__init__.py", line 1, in <module>
    from .ple import PLE
  File "/Users/Name/workspace/PyGame-Learning-Environment/ple/ple.py", line 5, in <module>
    from games import base

**Comment by ntasfi** [comment]
Hey @wjiangcmu how are you calling the package? Guessing via an example? Note: I have not tested this with python 3.x.

**Comment by wjiangcmu** [comment]
Yes, I was using python 3 in an example.

**Comment by StuartFarmer** [comment]
Same problem. Using Python 3.5.

**Comment by GregSatre** [comment]
I also have this issue. I followed the instructions from https://github.com/lusob/gym-ple and got this error when running gym_ple/example.py

**Comment by ntasfi** [comment]
Currently I have not tested it with python 3+. This was written to work with 2.7+. I can add support later, or will accept PRs, if there is enough need.
