### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by zergylord** [ntasfi/PyGame-Learning-Environment#22]
Wanting to use this alongside openai gym, but it doesn't seem to support python3. After installation, importing ple yields the error:
"No module named 'games'"
I'm assuming this is due to the import differences between the two versions; is this a known issue? Is python3 support planned?

**Comment by gregretkowski** [comment]
I just made a PR for this - https://github.com/ntasfi/PyGame-Learning-Environment/pull/23

**Comment by ntasfi** [comment]
I merged in the above PR by Greg.
