### ISSUE TITLE
Run without creating pygame window?

### ISSUE THREAD

**Issue by zergylord** [ntasfi/PyGame-Learning-Environment#26]
I know PLE has an argument to run without updating the screen, but the screen window is created regardless, which seems odd. I'm trying to run simulations on headless servers, but because of this bug I can't. Is there a work-around that I'm missing?

**Comment by wooridle** [comment]
I also experienced the same problem when running code in the Google cloud. I solved the problem this way. Add the following code to your code
`
os.putenv('SDL_VIDEODRIVER', 'fbcon')
os.environ["SDL_VIDEODRIVER"] = "dummy"
`
link : [http://www.pygame.org/wiki/HeadlessNoWindowsNeeded](url)

**Comment by ntasfi** [comment]
Thanks @wooridle!

**Comment by ntasfi** [comment]
Added to the readme, thanks again!

**Comment by icoxfog417** [comment]
I think `os.environ["SDL_VIDEODRIVER"] = "dummy"` is enough to do it.

http://www.pygame.org/wiki/HeadlessNoWindowsNeeded
