### ISSUE TITLE
Hi, I would like to join

### ISSUE THREAD

**Issue by sven1977** [ntasfi/PyGame-Learning-Environment#33]
Hi Norm,

Sorry to make this an "Issue", but I did not find any other way of contacting you.

My name is Sven, I am an AI/RL enthusiast with a PhD in Computational Biology and I would like to join forces with you. I just finished the Udacity deep learning nanodegree and am quite fluent in tensorflow, NN-topologies and RL-algos. Also, I have written my own Pygame/RL library (http://www.github.com/sven1977/shine), which is not fully functional yet. It's based on tmx files, through which one can define complete MDPs (games) that can then be solved by different RL algos. It heavily uses the concept of components, which are plug-and-play objects for game agents/enemies/etc.. (e.g. Physics). However, at this point - rather than reinventing the wheel - I would like to contribute to your lib and maybe merge mine (or ideas of it) with PLE. I have also implemented "The Lost Vikings" as a Pygame plugin for my lib (I like the fact that the levels in that game are extremely reward-sparse and would be nice challenges for RL algorithms). Please let me know if you are interested.

Best, Sven

**Comment by ntasfi** [comment]
Hey Sven! Yes, I welcome all contributions. Feel free to make a PR and I will review. This library is maintained in my spare time so I might not respond right away to a PR. I'm open to most changes, even core library, but those will take extra consideration.
