### ISSUE TITLE
Initial display screen

### ISSUE THREAD

**Issue by nishithbsk** [ntasfi/PyGame-Learning-Environment#4]
Hi,

Thanks for a great library! 

I had a question about the display_screen flag. Even when the flag is turned off, I see a black pygame window (see image attached) pop up. Is there a way to disable it?

Thanks!

<img width="292" alt="screen shot 2016-04-24 at 7 53 11 pm" src="https://cloud.githubusercontent.com/assets/4174989/14772715/51935b5e-0a56-11e6-83c0-5c151c80f6a6.png">

**Comment by ntasfi** [comment]
Hey! So this pops up by when you initialize PyGame, regardless of its usage with PLE, whether or not you draw anything to the game frame. Currently I don't believe it can be disabled but I am looking into it as I eventually want PLE to run without a display system (headless server etc.). 

I usually just minimize the frame or make use of it during testing loops to show me how the agent is performing, so its not completely annoying.

**Comment by nishithbsk** [comment]
Thanks for the clarification!

**Comment by floringogianu** [comment]
@ntasfi @nishithbsk Any chance this could maybe be disabled? I am experimenting with spawning the environment on multiple processes and windows popping all over the screen can get a bit annoying.
