### ISSUE TITLE
in flappy bird game action takes a value of 119

### ISSUE THREAD

**Issue by adibyte95** [ntasfi/PyGame-Learning-Environment#53]
p.act(action) 

action takes a value of 119 to push the bird upwards 
119 is  ASCII number for w which is used in games for upward/forward movement.

but since this game has only two possible action it would be better if it is 0/1

**Comment by ntasfi** [comment]
@adibyte95 the library was built around pygame which exposes "keys" as constants. It felt natural write the games using these key constants. You can use the `getActionSet()` function to retrieve all the keys, this way you dont need to worry about what the actual underlying code is.
