### ISSUE TITLE
Redundancy in Dockerfile?

### ISSUE THREAD

**Issue by prodicus** [ntasfi/PyGame-Learning-Environment#9]
I am referring to there two lines [here](https://github.com/ntasfi/PyGame-Learning-Environment/blob/196f9e9915c0fca9dfe74a7f671f26fea6482b4a/docker/Dockerfile#L61-L62)

Could you explain why did you clone your repo twice here?

**Comment by EderSantana** [comment]
the first one installs the package and the other just copies a local version for development

**Comment by prodicus** [comment]
Thanks for that :)

**Comment by prodicus** [comment]
@EderSantana Could you look at this issue #10 if you are feeling like it? I am not able to run the ple.
